# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.core.management import call_command
from django.db import migrations


def initial_data(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={
            'domain': 'awesomegame.sterenczak.me',
            'name': 'AwesomeGame'
        }
    )

    call_command('loaddata', 'initial_users')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data, reverse_code=do_nothing)
    ]
