# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('awesome_rooms', '0002_auto_20170531_1858'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='server.GameServer')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='awesome_rooms.Room')),
            ],
            options={
                'db_table': 'room_game_server',
            },
        ),
    ]
