# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 19:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_server_status(apps, schema_editor):
    GameServerStatus = apps.get_model('server', 'GameServerStatus')
    GameServerStatus.objects.bulk_create([
        GameServerStatus(status=1, name="Dostępny"),
        GameServerStatus(status=2, name="W użyciu"),
        GameServerStatus(status=9, name="Zawieszony"),
    ])


def delete_intial_server_status(apps, schema_editor):
    GameServerStatus = apps.get_model('server', 'GameServerStatus')
    GameServerStatus.objects.get(status__in=[1, 2, 9]).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, unique=True, verbose_name='Nazwa')),
                ('slug', models.SlugField()),
                ('url', models.URLField(unique=True, verbose_name='Adres URL')),
                ('auth_token', models.CharField(max_length=256, verbose_name='Token uwierzytelniaj\u0105cy')),
                ('datadog_hostname', models.CharField(max_length=256, verbose_name='Nazwa hosta w datadog')),
            ],
        ),
        migrations.CreateModel(
            name='GameServerStatus',
            fields=[
                ('status', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RunPython(create_initial_server_status, reverse_code=delete_intial_server_status),
        migrations.AddField(
            model_name='gameserver',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='server.GameServerStatus'),
        ),
    ]
