# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:44
from __future__ import unicode_literals

from autoslug.utils import slugify
from django.db import migrations, models



def add_slug(apps, schema_editor):

    Model = apps.get_model('server', 'GameServer')

    for game_server in Model.objects.all():
        if game_server.slug is None:
            game_server.slug = slugify(game_server.name)

        game_server.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_load_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(add_slug),
        migrations.AlterField(
            model_name='gameserver',
            name='slug',
            field=models.SlugField()
        )
    ]
